#!/usr/bin/env bash

set -x

exec docker run -it \
  --mount type=bind,source=.,target=/source \
  -e YT_MODE=external \
  -e YT_PROXY="${YT_PROXY}" \
  -e YT_TOKEN="${YT_TOKEN}" \
  -e PYTHONPATH="/source:$PYTHONPATH" \
  cr.ai.nebius.cloud/crnf2coti090683j5ssi/tractorun/torchesaurus_tests:2024-06-07-19-46-14 \
  pytest /source/tests/$1 ${@:2}
