#!/usr/bin/env bash

set -x

exec docker run -it \
  --mount type=bind,source=.,target=/src \
  --network=host \
  -e YT_MODE=external \
  -e YT_PROXY="${YT_PROXY}" \
  -e YT_TOKEN="${YT_TOKEN}" \
  -e PYTHONPATH="/src:$PYTHONPATH" \
  cr.ai.nebius.cloud/crnf2coti090683j5ssi/tractorun/torchesaurus_tests:2024-06-17-15-21-24 \
  pytest /src/tests/generic/$1 ${@:2}
