#!/usr/bin/env bash

set -x

exec docker run -it \
  --mount type=bind,source=.,target=/src \
  --network=host \
  -e YT_MODE=external \
  -e YT_PROXY="${YT_PROXY}" \
  -e YT_TOKEN="${YT_TOKEN}" \
  -e PYTHONPATH="/src:$PYTHONPATH" \
  cr.ai.nebius.cloud/crnf2coti090683j5ssi/tractorun/tensorproxy_tests:2024-08-06-22-05-28 \
  pytest /src/tests/tensorproxy/$1 ${@:2}
