#!/usr/bin/env bash

set -x

IMAGE_GENERIC="cr.ai.nebius.cloud/crnf2coti090683j5ssi/tractorun/tractorch_tests:2024-11-19-18-49-57"
IMAGE_TENSORPROXY="cr.ai.nebius.cloud/crnf2coti090683j5ssi/tractorun/tensorproxy_tests:2024-10-14-15-02-56"

PATH_GENERIC="/src/tests/generic"
PATH_TENSORPROXY="/src/tests/tensorproxy"

TEST_TYPE="${1:-all}"

IMAGES=()
TEST_PATHS=()

case "$TEST_TYPE" in
  "generic")
    IMAGES=("$IMAGE_GENERIC")
    TEST_PATHS=("$PATH_GENERIC")
    ;;
  "tensorproxy")
    IMAGES=("$IMAGE_TENSORPROXY")
    TEST_PATHS=("$PATH_TENSORPROXY")
    ;;
  "all")
    IMAGES=("$IMAGE_GENERIC" "$IMAGE_TENSORPROXY")
    TEST_PATHS=("$PATH_GENERIC" "$PATH_TENSORPROXY")
    ;;
  *)
    echo "Invalid test type: $TEST_TYPE. Choose from 'all', 'tensorproxy', or 'generic'."
    exit 1
    ;;
esac

run_tests() {
  local image=$1
  local test_path=$2
  docker run -it \
    --mount type=bind,source=.,target=/src \
    --network=host \
    -e YT_MODE=external \
    -e YT_PROXY="${YT_PROXY}" \
    -e YT_TOKEN="${YT_TOKEN}" \
    -e PYTHONPATH="/src:$PYTHONPATH" \
    -e PYTHONDONTWRITEBYTECODE=1 \
    "$image" \
    pytest "$test_path" "${@:3}"
}

for i in "${!IMAGES[@]}"; do
  if [[ "$2" == -* ]]; then
    TEST_NAME=""
    TEST_ARGS=${@:2}
  else
    TEST_NAME=$2
    TEST_ARGS=${@:3}
  fi
  run_tests "${IMAGES[$i]}" "${TEST_PATHS[$i]}/$TEST_NAME" $TEST_ARGS
done
