#!/usr/bin/env bash

set -x

exec docker run -it \
  --mount type=bind,source=.,target=/source \
  -e YT_MODE=external \
  -e YT_PROXY="${YT_PROXY}" \
  -e YT_TOKEN="${YT_TOKEN}" \
  -e PYTHONPATH="/source:$PYTHONPATH" \
  cr.ai.nebius.cloud/crnf2coti090683j5ssi/tractorun/torchesaurus_runtime:2024-06-05-19-24-41 \
  $1 ${@:2}
