name: isort
on: [pull_request]

jobs:
  build:
    runs-on: tractoai-runners
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: pip install .[dev]
    - run: make isort-check
