name: mypy
on: [pull_request]

jobs:
  build:
    runs-on: tractoai-runners-default
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: make mypy-check
