name: Build and upload to internal pypi

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true

jobs:
  build-and-upload:
    runs-on: tractoai-runners
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
         ref: ${{ inputs.tag }}

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Install requirements"
        run: pip install -r requirements_dev.txt

      - name: "Build a wheel"
        run: "pip wheel . -w dist --no-deps"

      - name: "Upload the wheel"
        env:
          TWINE_USERNAME: svc-yt-dev@nebius.com
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_NON_INTERACTIVE: "1"
          TWINE_REPOSITORY_URL: "https://artifactory.nebius.dev/artifactory/api/pypi/nyt"
        run: "twine upload -r local dist/tractorun-${{ inputs.tag }}-py3-none-any.whl"
