name: Create release

on:
  workflow_dispatch: {}

jobs:
  create-release:
    runs-on: tractoai-runners
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # pull all the commits

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Install requirements"
        run: pip install requirements_dev.txt

      - name: "Setup git"
        run: git config --global user.email "noreply@tracto.ai" && git config --global user.name "Tracto Driver"

      - name: "Generate changelog"
        run: generate-changelog

      - name: "Bump version"
        run: bump-my-version bump minor

      - name: "Grab the tag"
        id: tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: "Create Pull Request"
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          title: "New version is coming: ${{ steps.tag.outputs.tag }}"
          branch: "new-version-${{ steps.tag.outputs.tag }}"
          body: ""

      - name: "Merge Pull Request"
        run: gh pr merge --squash --admin ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set tag"
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tag.outputs.tag }}
          tag_prefix: ""
