name: style_checker
on: [pull_request]

jobs:
  black:
    runs-on: tractoai-runners
    container:
      image: cr.ai.nebius.cloud/crnf2coti090683j5ssi/gh_runner:0.0.4
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: pip install .[dev]
    - run: make black-check
  ruff:
    runs-on: tractoai-runners
    container:
      image: cr.ai.nebius.cloud/crnf2coti090683j5ssi/gh_runner:0.0.4
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: pip install .[dev]
    - run: make ruff-check
  isort:
    runs-on: tractoai-runners
    container:
      image: cr.ai.nebius.cloud/crnf2coti090683j5ssi/gh_runner:0.0.4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install .[dev]
      - run: make isort-check
