name: tests

on:
  pull_request: {}

jobs:
  generic:
    runs-on: tractoai-runners
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt -r requirements_tests.txt
      - run: pip install --index-url https://download.pytorch.org/whl/cpu -r requirements_torch.txt
      - run: pip install --no-deps .
      - run: pytest tests/generic -n 4 -s
        env:
          YT_MODE: testcontainers
          TRACTORUN_YT_CONFIG_FOR_JOB_PATCH: '{proxy={url="http://localhost:80"}}'

  tensorproxy:
    runs-on: tractoai-runners
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt -r requirements_tests.txt
      - run: pip install --extra-index-url https://artifactory.nebius.dev/artifactory/api/pypi/nyt/simple -r requirements_tensorproxy.txt
      - run: pip install --no-deps .
      - run: pytest tests/tensorproxy -s
        env:
          YT_MODE: testcontainers
          TRACTORUN_YT_CONFIG_FOR_JOB_PATCH: '{proxy={url="http://localhost:80"}}'
